# Generated by Django 5.1.7 on 2025-04-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
