# Generated by Django 5.1.7 on 2025-04-09 10:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when this entry was created in the system",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the table data was last updated in the system",
                    ),
                ),
                (
                    "internal_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identification number for the table.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is active?"),
                ),
                ("slug", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Description",
                "verbose_name_plural": "Descriptions",
                "db_table": "descriptions",
            },
        ),
        migrations.CreateModel(
            name="RateBy",
            fields=[
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when this entry was created in the system",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the table data was last updated in the system",
                    ),
                ),
                (
                    "internal_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identification number for the table.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is active?"),
                ),
                ("slug", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Rateby",
                "verbose_name_plural": "Ratebys",
                "db_table": "ratebys",
            },
        ),
        migrations.CreateModel(
            name="Desc_RateBy",
            fields=[
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when this entry was created in the system",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the table data was last updated in the system",
                    ),
                ),
                (
                    "internal_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identification number for the table.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is active?"),
                ),
                (
                    "description",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disc.description",
                    ),
                ),
                ("rateBy", models.ManyToManyField(to="disc.rateby")),
            ],
            options={
                "verbose_name": "Desc_Rateby",
                "verbose_name_plural": "Desc_Ratebys",
                "db_table": "desc_ratebys",
            },
        ),
    ]
