# Generated by Django 5.1.7 on 2025-04-10 07:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseActivity",
            fields=[
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when this entry was created in the system",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the table data was last updated in the system",
                    ),
                ),
                (
                    "internal_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identification number for the table.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is active?"),
                ),
                ("activity_id", models.CharField(max_length=50, unique=True)),
                ("activity_type", models.CharField(max_length=50)),
                ("warehouse_number", models.CharField(max_length=20)),
                ("company_number", models.IntegerField()),
                ("purchase_order", models.CharField(max_length=20)),
                ("uom", models.CharField(max_length=50)),
                ("wh_pull_date", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
