# Generated by Django 5.1.7 on 2025-04-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskManager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="source",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
